app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user_list:
    path:      /users
    defaults:  { _controller: AppBundle:User:index }